version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_pgvector
    restart: unless-stopped
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "55432:5432"   # ⬅️ host:container
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - pgnet

volumes:
  postgres_data:

networks:
  pgnet:
